name: Sync fork with source repo

on:
  workflow_dispatch: # enable workflow to be started manually
  schedule:
    - cron: '* * 1 * *' # first day of every month

jobs:
  sync-fork:
    name: Sync Fork

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.SFDX_ROOT }}

    steps:
      - name: Checkout force-di
        uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.SAGE_PEOPLE_CI_USER_PAT }}

      - name: Merge the changes from the upstream default branch
        env:
          GH_TOKEN: ${{ secrets.SAGE_PEOPLE_CI_USER_PAT }}
        run: |
          gh repo sync 
    
  